url: https://florianstrob.github.io
baseurl: /

# Site settings
title: Florian Strob
email: your-email@domain.com
description: "Portfolio"


# Team names, titles and social links
people:
- name: Florian Strob
  pic: 1
  position: Architecture & Literature
  social:
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://twitter.com/jekyllrb

# Build settings
markdown: kramdown
permalink: pretty
